# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='products')),
                ('available', models.BooleanField(default=False)),
                ('presentacion', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, choices=[('Mexico', 'México'), ('Francia', 'Francia'), ('Italia', 'Italia'), ('NuevaZelanda', 'Nueva Zelanda'), ('Chile', 'Chile'), ('Portugal', 'Portugal'), ('Espana', 'España'), ('Alemania', 'Alemania')], max_length=10, null=True)),
                ('slug', models.SlugField(max_length=200, unique_for_date='creado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalogo.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_drink', to='catalogo.TypeProduct'),
        ),
        migrations.AddField(
            model_name='category',
            name='type_product',
            field=models.ManyToManyField(related_name='type_product', to='catalogo.TypeProduct'),
        ),
    ]
