# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_drink', to='catalogo.TypeProduct'),
        ),
    ]
